/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as SneakersRouteImport } from './routes/sneakers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const SneakersRoute = SneakersRouteImport.update({
  id: '/sneakers',
  path: '/sneakers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecoes': typeof ColecoesRoute
  '/lancamentos': typeof LancamentosRoute
  '/sneakers': typeof SneakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecoes': typeof ColecoesRoute
  '/lancamentos': typeof LancamentosRoute
  '/sneakers': typeof SneakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecoes': typeof ColecoesRoute
  '/lancamentos': typeof LancamentosRoute
  '/sneakers': typeof SneakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colecoes' | '/lancamentos' | '/sneakers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colecoes' | '/lancamentos' | '/sneakers'
  id: '__root__' | '/' | '/colecoes' | '/lancamentos' | '/sneakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColecoesRoute: typeof ColecoesRoute
  LancamentosRoute: typeof LancamentosRoute
  SneakersRoute: typeof SneakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneakers': {
      id: '/sneakers'
      path: '/sneakers'
      fullPath: '/sneakers'
      preLoaderRoute: typeof SneakersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColecoesRoute: ColecoesRoute,
  LancamentosRoute: LancamentosRoute,
  SneakersRoute: SneakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
